formatter: markdown table
header-from: doc.tf

# output:
#   file: README.md
#   mode: inject
#   template: |-
#     <!--- BEGIN_TF_DOCS --->
#     {{ .Content }}
#     <!--- END_TF_DOCS --->

sort:
  enabled: true
  by: required

settings:
  indent: 2
  required: true
