name: Build

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    name: Documentations
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Regenerate README.md
        uses: terraform-docs/gh-actions@main
        with:
          working-dir: .
          output-file: README.md
          config-file: .terraform-docs.yml
          git-push: true
          git-push-user-name: Khosrow Moossavi
          git-commit-message: "terraform-docs: automated action"
          git-push-sign-off: true
          template: |-
            # FOSDEM21 terraform-docs Demo

            This is a demo project to show how to automatically generate documentations of
            Terraform modules with [terraform-docs] using [terraform-docs/gh-actions].

            <!--- BEGIN_TF_DOCS --->
            <!--- END_TF_DOCS --->

            [terraform-docs]: https://github.com/terraform-docs/terraform-docs
            [terraform-docs/gh-actions]: https://github.com/terraform-docs/gh-actions

            <!-- DO NOT EDIT! auto-generated by terraform-docs. -->
