name: Build

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    name: Documentations
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Regenerate README.md
        uses: terraform-docs/gh-actions@v0.4.0
        with:
          working-dir: .
          output-file: README.md
          config-file: .terraform-docs.yml
          git-push: true
          git-push-user-name: Khosrow Moossavi
          git-commit-message: "terraform-docs: automated action"
          git-push-sign-off: true
